project:
  type: website
  output-dir: _site
  render:
    - "*.md"
    - "!COURSE_MASTER_PLAN.md"
    - "!AGENTS.md"
    - "!README.md"
    - "precurso/"
    - "presentaciones/"
    - "practicos/"
    - "!admin/"
    - "!communications_outreach/"
    - "!budget-funding/"
    - "!registration-selection/"


website:
  title: "🔬 Taller de Fundamentos en Análisis de Bioimágenes (Formación de Formadores)"
  favicon: "media/cma_logo.svg"
  open-graph: true
  twitter-card: true
  site-url: https://acorbat.github.io/2026_TtT_Course/
  repo-url: https://github.com/acorbat/2026_TtT_Course/
  issue-url: https://github.com/acorbat/2026_TtT_Course/issues/new
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  page-footer:
    center:
      - text: "This work is licensed under a CC-BY-NC 4.0 International License."
        href: https://creativecommons.org/licenses/by-nc/4.0/deed.en

  navbar:
    tools:
      - icon: github
        href: https://github.com/acorbat/2026_TtT_Course/
        text: GitHub

  sidebar:
    style: "docked"
    search: true
    contents:
      - index.md
      - title: "Programa"
        href: program.md
      - section: "Precurso"
        href: precurso/index.md
        contents:
          - precurso/cli.md
          - precurso/fiji.md
          - precurso/python.md
      - section: "Presentaciones"
        contents:
          - presentaciones/que_es_bia.md
          - presentaciones/segmentacion_clasica_cuantificacion.md
          - presentaciones/workflows.md
          - presentaciones/machine_learning.md
          - presentaciones/deep_learning.md
          - presentaciones/deep_learning_biomodels.md
          - presentaciones/teaching.md
          - presentaciones/ai_in_bia.md
      - section: "Prácticos"
        contents:
          - practicos/workshop_2d_images.md
          - practicos/segmentation_quantification.md
          - practicos/interfaces.md
          - practicos/git_pixi.md
          - practicos/machine_learning.md
          - practicos/object_classification.md
          - practicos/other_tools.md
          - practicos/deep_learning_generic.md
          - practicos/deep_learning_biomodels.md
      - resources.md

bibliography: references.bib

format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true
    toc-depth: 4
    code-copy: true
    code-overflow: wrap
    lightbox: true