project:
  type: website
  output-dir: _site
  render:
    - "*.md"
    - "!COURSE_MASTER_PLAN.md"
    - "!AGENTS.md"
    - "!README.md"
    - "practicos/"
    - "presentaciones/"
    - "!admin/"
    - "!communications_outreach/"
    - "!budget-funding/"
    - "!registration-selection/"


website:
  title: "🔬 Fundamentos en Análisis de Bioimágenes (*Train-the-Trainer*)"
  favicon: "media/lisium.svg"
  open-graph: true
  twitter-card: true
  site-url: https://acorbat.github.io/2026_TtT_Course/
  repo-url: https://github.com/acorbat/2026_TtT_Course/
  issue-url: https://github.com/acorbat/2026_TtT_Course/issues/new
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  page-footer:
    center:
      - text: "This work is licensed under a CC-BY-NC 4.0 International License."
        href: https://creativecommons.org/licenses/by-nc/4.0/deed.en

  navbar:
    tools:
      - icon: github
        href: https://github.com/acorbat/2026_TtT_Course/
        text: GitHub

  sidebar:
    style: "floating"
    contents: auto

bibliography: references.bib

format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true
    toc-depth: 4
    code-copy: true
    code-overflow: wrap
    lightbox: true